name: "angel_build_runner"
dependencies: 
  angel_framework: ">=1.1.0 <2.0.0"
  angel_shelf: ">=1.1.0 <2.0.0"
  angel_static: ^1.3.0
  build_runner: ">=0.6.1 <2.0.0"
dev_dependencies: 
  build_web_compilers: "^0.1.1"
  console: "^2.2.4"
dependency_overrides:
  build_config: ^0.2.1
  built_collection: ^2.0.0